import { IEcontOffice, IncomingOfficeData } from '../types';

export default function mapOfficeData(from: IncomingOfficeData): IEcontOffice {
  return {
    id: from.id,
    code: from.code,
    is_mps: from.isMPS,
    is_aps: from.isAPS,
    name: from.name,
    name_en: from.nameEn,
    phones: from.phones,
    emails: from.emails,
    info: from.info,
    currency: from.currency,
    language: from.language,
    normal_business_hours_from: from.normalBusinessHoursFrom,
    normal_business_hours_to: from.normalBusinessHoursTo,
    half_day_business_hours_from: from.halfDayBusinessHoursFrom,
    half_day_business_hours_to: from.halfDayBusinessHoursTo,
    sunday_business_hours_from: from.sundayBusinessHoursFrom,
    sunday_business_hours_to: from.sundayBusinessHoursTo,
    shipment_types: from.shipmentTypes,
    partner_code: from.partnerCode,
    hub_code: from.hubCode,
    hub_name: from.hubName,
    hub_name_en: from.hubNameEn,
    is_drive: from.isDrive,
    city_fk: from.address.city.id,
    city_name: from.address.city.name.toLowerCase(),
    city_name_en: from.address.city.nameEn.toLowerCase(),
    post_code: from.address.city.postCode,
    full_address: from.address.fullAddress,
    full_address_en: from.address.fullAddressEn,
    quarter: from.address.quarter,
    street: from.address.street,
    num: from.address.num,
    other: from.address.other,
    zip: from.address.zip,
    hezid: from.address.hezid,
    latitude: from.address.location.latitude,
    longitude: from.address.location.longitude,
    confidence: from.address.location.confidence
  };
}